// Autogenerated from Pigeon (v17.1.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class DeviceInfoModel {
  DeviceInfoModel({
    this.name,
  });

  String? name;

  Object encode() {
    return <Object?>[
      name,
    ];
  }

  static DeviceInfoModel decode(Object result) {
    result as List<Object?>;
    return DeviceInfoModel(
      name: result[0] as String?,
    );
  }
}

class _DeviceInfoManagerCodec extends StandardMessageCodec {
  const _DeviceInfoManagerCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is DeviceInfoModel) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return DeviceInfoModel.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// FLUTTER FRAMEWORK -> FLUTTER ENGINE
class DeviceInfoManager {
  /// Constructor for [DeviceInfoManager].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeviceInfoManager({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _DeviceInfoManagerCodec();

  Future<DeviceInfoModel> getDeviceInfo() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.pigeon_plugin.DeviceInfoManager.getDeviceInfo';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as DeviceInfoModel?)!;
    }
  }
}

class _FlutterVersionManagerCodec extends StandardMessageCodec {
  const _FlutterVersionManagerCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is DeviceInfoModel) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return DeviceInfoModel.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// FLUTTER FRAMEWORK <- FLUTTER ENGINE
abstract class FlutterVersionManager {
  static const MessageCodec<Object?> pigeonChannelCodec = _FlutterVersionManagerCodec();

  void deviceInfo(DeviceInfoModel deviceInfoModel);

  static void setup(FlutterVersionManager? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pigeon_plugin.FlutterVersionManager.deviceInfo', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pigeon_plugin.FlutterVersionManager.deviceInfo was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final DeviceInfoModel? arg_deviceInfoModel = (args[0] as DeviceInfoModel?);
          assert(arg_deviceInfoModel != null,
              'Argument for dev.flutter.pigeon.pigeon_plugin.FlutterVersionManager.deviceInfo was null, expected non-null DeviceInfoModel.');
          try {
            api.deviceInfo(arg_deviceInfoModel!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
